/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entidad.Producto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class FrameBebidas extends javax.swing.JFrame {

    /**
     * Creates new form FrameBebidas
     */
    public FrameBebidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCompraUnitaria3 = new javax.swing.JButton();
        btnAgregar2 = new javax.swing.JButton();
        btnAgregar3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnIrMenuPrincipal = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        btnCompraUnitaria1 = new javax.swing.JButton();
        btnCompraUnitaria2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        miSpinner2 = new javax.swing.JSpinner();
        miSpinner3 = new javax.swing.JSpinner();
        miSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bebidas ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 60, 40));

        jLabel3.setText("Precio :  3.00");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        btnCompraUnitaria3.setText("Compra unitaria");
        btnCompraUnitaria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraUnitaria3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompraUnitaria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        btnAgregar2.setText("Agregar");
        getContentPane().add(btnAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        btnAgregar3.setText("Agregar");
        getContentPane().add(btnAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        jLabel2.setText("Precio : 2.50");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, 20));

        jLabel4.setText("Precio : 1.50 ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\OneDrive\\Escritorio\\imagenes\\cocacola.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\OneDrive\\Escritorio\\imagenes\\agua.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\OneDrive\\Escritorio\\imagenes\\incacola.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        btnIrMenuPrincipal.setText("Menu Principal");
        btnIrMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnIrMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jButton4.setText("Ir Carrito");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 110, -1));

        btnAgregar1.setText("Agregar");
        getContentPane().add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        btnCompraUnitaria1.setText("Compra unitaria");
        btnCompraUnitaria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraUnitaria1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompraUnitaria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        btnCompraUnitaria2.setText("Compra unitaria");
        btnCompraUnitaria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraUnitaria2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompraUnitaria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel8.setText("COCA COLA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel9.setText("AGUA CIELO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel10.setText("INCA KOLA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        miSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        getContentPane().add(miSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        miSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        getContentPane().add(miSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        miSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        miSpinner1.setMaximumSize(new java.awt.Dimension(100, 100));
        miSpinner1.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(miSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrMenuPrincipalActionPerformed
        FrameMenuPrincipal dani = new FrameMenuPrincipal();
        dani.setVisible(true);
        dani.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnIrMenuPrincipalActionPerformed

    private void btnCompraUnitaria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraUnitaria1ActionPerformed
         String nombre="coca cola";
         double precio=3.00;
         int categoria=1;
         int cantidad=(int)miSpinner1.getValue();
         Producto pro=new Producto(nombre, precio, categoria);
         FrameCarrito x=new FrameCarrito();
         x.txtTotal.setText(Double.toString(cantidad*precio));
         DefaultTableModel mdetalle = (DefaultTableModel) x.tblCompraUnitaria.getModel();
         Object fila[]={nombre,precio,cantidad,categoria};
         mdetalle.addRow(fila);
         
         //x.tblCompraUnitaria;
         x.setVisible(true);
         x.setLocationRelativeTo(null);
         this.dispose();
        
    }//GEN-LAST:event_btnCompraUnitaria1ActionPerformed

    private void btnCompraUnitaria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraUnitaria2ActionPerformed
        String nombre="agua cielo";
         double precio=1.50;
         int categoria=1;
         int cantidad=(int)miSpinner2.getValue();
         Producto pro=new Producto(nombre, precio, categoria);
         FrameCarrito x=new FrameCarrito();
         x.txtTotal.setText(Double.toString(cantidad*precio));
         DefaultTableModel mdetalle = (DefaultTableModel) x.tblCompraUnitaria.getModel();
         Object fila[]={nombre,precio,cantidad,categoria};
         mdetalle.addRow(fila);
         
         //x.tblCompraUnitaria;
         x.setVisible(true);
         x.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_btnCompraUnitaria2ActionPerformed

    private void btnCompraUnitaria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraUnitaria3ActionPerformed
        String nombre="inca kola";
         double precio=2.50;
         int categoria=1;
         int cantidad=(int)miSpinner3.getValue();
         Producto pro=new Producto(nombre, precio, categoria);
         FrameCarrito x=new FrameCarrito();
         x.txtTotal.setText(Double.toString(cantidad*precio));
         DefaultTableModel mdetalle = (DefaultTableModel) x.tblCompraUnitaria.getModel();
         Object fila[]={nombre,precio,cantidad,categoria};
         mdetalle.addRow(fila);
         
         //x.tblCompraUnitaria;
         x.setVisible(true);
         x.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_btnCompraUnitaria3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnCompraUnitaria1;
    private javax.swing.JButton btnCompraUnitaria2;
    private javax.swing.JButton btnCompraUnitaria3;
    private javax.swing.JButton btnIrMenuPrincipal;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner miSpinner1;
    private javax.swing.JSpinner miSpinner2;
    private javax.swing.JSpinner miSpinner3;
    // End of variables declaration//GEN-END:variables
}
